name: styled_text_example
description: Demonstrates how to use 'Styled Text'.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  styled_text:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
